version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ifome-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ifome_db
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: